excluded:
- Carthage

disabled_rules:
- statement_position

enabled_rules:
- empty_count
#- missing_docs

cyclomatic_complexity:
  - 12 # Increased from 10

force_try:
  severity: warning

function_body_length:
  - 41 # Up from 40

line_length:
  warning: 212
  error: 256

todo:
  severity: warning

type_name:
  excluded:
    - STAP_A
    - STAP_B
    - FU_A
    - FU_B

valid_docs:
  severity: warning

variable_name:
  excluded:
    - nal_ref_idc
    - forbidden_zero_bit
