language: objective-c
osx_image: xcode7.2
before_install:
- brew update > /dev/null
- brew install carthage > /dev/null
before_script:
- carthage bootstrap
script:
- xctool -project SwiftRTP.xcodeproj -scheme SwiftRTP iOS Demo -sdk iphonesimulator build test
- xctool -project SwiftRTP.xcodeproj -scheme SwiftRTP Mac Demo build test
- xctool -project SwiftRTP.xcodeproj -scheme SwiftRTP_iOS -sdk iphonesimulator build test
- xctool -project SwiftRTP.xcodeproj -scheme SwiftRTP_OSX build test

